//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "artifact_set_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub set_id: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub path: String,
    pub oid: String,
    pub size_bytes: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub content_type: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "oid",
        to = "oid",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    pub artifact_objects: BelongsTo<super::artifact_objects::Entity>,
    #[sea_orm(
        belongs_to,
        from = "set_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub artifact_sets: BelongsTo<super::artifact_sets::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
