//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "artifact_sets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "ux_artifact_sets_repo_namespace_type_set_id")]
    pub repo: String,
    #[sea_orm(unique_key = "ux_artifact_sets_repo_namespace_type_set_id")]
    pub namespace: String,
    #[sea_orm(unique_key = "ux_artifact_sets_repo_namespace_type_set_id")]
    pub object_type: String,
    #[sea_orm(unique_key = "ux_artifact_sets_repo_namespace_type_set_id")]
    pub artifact_set_id: String,
    pub metadata: Option<Json>,
    pub created_by: Option<String>,
    pub created_at: DateTime,
    pub expires_at: Option<DateTime>,
    #[sea_orm(has_many, via = "artifact_set_files")]
    pub artifact_objects: HasMany<super::artifact_objects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
