//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "artifact_objects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub oid: String,
    pub size_bytes: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub content_type: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub storage_key: String,
    pub created_at: DateTime,
    pub last_seen_at: DateTime,
    pub integrity: Option<Json>,
    #[sea_orm(has_many, via = "artifact_set_files")]
    pub artifact_sets: HasMany<super::artifact_sets::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
