//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::{ActorTypeEnum, AuditActionEnum, TargetTypeEnum};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "audit_logs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub actor_id: i64,
    pub actor_type: ActorTypeEnum,
    pub action: AuditActionEnum,
    pub target_type: TargetTypeEnum,
    pub target_id: i64,
    pub metadata: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
