//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::{InstallationBotStatusEnum, InstallationTargetTypeEnum};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "bot_installations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_bot_installations_target")]
    pub bot_id: i64,
    #[sea_orm(unique_key = "uq_bot_installations_target")]
    pub target_type: InstallationTargetTypeEnum,
    #[sea_orm(unique_key = "uq_bot_installations_target")]
    pub target_id: i64,
    pub status: InstallationBotStatusEnum,
    pub installed_by: i64,
    pub installed_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "bot_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub bots: BelongsTo<super::bots::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
