//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "bot_keys")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub bot_id: i64,
    pub private_key: String,
    pub public_key: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "bot_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub bots: BelongsTo<super::bots::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
