//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "bot_tokens")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_bot_tokens_name_hash")]
    pub bot_id: i64,
    #[sea_orm(unique_key = "uq_bot_tokens_name_hash")]
    pub token_hash: String,
    #[sea_orm(unique_key = "uq_bot_tokens_name_hash")]
    pub token_name: String,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub revoked: bool,
    #[sea_orm(
        belongs_to,
        from = "bot_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub bots: BelongsTo<super::bots::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
