//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::{BotStatusEnum, PermissionScopeEnum};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "bots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_bots_name_org")]
    pub name: String,
    #[sea_orm(unique_key = "uq_bots_name_org")]
    pub organization_id: Option<i64>,
    pub creator_user_id: i64,
    pub permission_scope: PermissionScopeEnum,
    pub status: BotStatusEnum,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub bot_installations: HasMany<super::bot_installations::Entity>,
    #[sea_orm(has_many)]
    pub bot_keys: HasMany<super::bot_keys::Entity>,
    #[sea_orm(has_many)]
    pub bot_tokens: HasMany<super::bot_tokens::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
