//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "buck_session_file")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "uk_session_file")]
    pub session_id: String,
    #[sea_orm(column_type = "Text", unique_key = "uk_session_file")]
    pub file_path: String,
    pub file_size: i64,
    pub file_hash: String,
    pub file_mode: Option<String>,
    pub upload_status: String,
    pub upload_reason: Option<String>,
    pub blob_id: Option<String>,
    pub uploaded_at: Option<DateTime>,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "session_id",
        to = "session_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub buck_session: BelongsTo<super::buck_session::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
