//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "buck_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub session_id: String,
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub repo_path: String,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub commit_message: Option<String>,
    pub from_hash: Option<String>,
    pub expires_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub buck_session_files: HasMany<super::buck_session_file::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
