//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "build_triggers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub trigger_type: String,
    pub trigger_source: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub trigger_payload: Json,
    pub trigger_time: DateTime,
    pub task_id: Option<Uuid>,
    pub updated_at: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
