//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "build_targets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub task_id: Uuid,
    pub path: String,
    #[sea_orm(column_type = "Text")]
    pub latest_state: String,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub orion_tasks: BelongsTo<super::orion_tasks::Entity>,
    #[sea_orm(has_many)]
    pub target_state_histories: HasMany<super::target_state_histories::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
