//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "campsite_member_identity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub campsite_user_id: String,
    pub username: String,
    pub github_login: Option<String>,
    pub display_name: String,
    pub email: String,
    pub updated_at: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
