//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "commit_auths")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub commit_sha: String,
    pub matched_username: Option<String>,
    pub is_anonymous: bool,
    pub matched_at: Option<DateTime>,
    pub created_at: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
