//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "email_jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub username: String,
    pub to_email: String,
    pub event_type_code: String,
    #[sea_orm(column_type = "Text")]
    pub subject: String,
    #[sea_orm(column_type = "Text")]
    pub body_html: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub body_text: Option<String>,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub retry_count: i32,
    pub next_retry_at: Option<DateTime>,
    pub sent_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "event_type_code",
        to = "code",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    pub notification_event_types: BelongsTo<super::notification_event_types::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
