//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "git_tag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub repo_id: i64,
    #[sea_orm(unique)]
    pub tag_id: String,
    pub object_id: String,
    pub object_type: String,
    #[sea_orm(column_type = "Text")]
    pub tag_name: String,
    #[sea_orm(column_type = "Text")]
    pub tagger: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub created_at: DateTime,
    pub pack_id: String,
    pub pack_offset: i64,
}

impl ActiveModelBehavior for ActiveModel {}
