//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "git_blob")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "uniq_b_git_repo")]
    pub repo_id: i64,
    #[sea_orm(unique_key = "uniq_b_git_repo")]
    pub blob_id: String,
    pub name: Option<String>,
    pub size: i32,
    pub created_at: DateTime,
    pub pack_id: String,
    pub file_path: String,
    pub pack_offset: i64,
    pub is_delta_in_pack: bool,
}

impl ActiveModelBehavior for ActiveModel {}
