//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::RefTypeEnum;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "import_refs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "uniq_ref_path_name")]
    pub repo_id: i64,
    #[sea_orm(column_type = "Text", unique_key = "uniq_ref_path_name")]
    pub ref_name: String,
    pub ref_git_id: String,
    pub ref_type: RefTypeEnum,
    pub default_branch: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
