//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::ReferenceTypeEnum;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "issue_cl_references")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub target_id: String,
    pub reference_type: ReferenceTypeEnum,
}

impl ActiveModelBehavior for ActiveModel {}
