//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "lfs_objects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub oid: String,
    pub size: i64,
    pub exist: bool,
}

impl ActiveModelBehavior for ActiveModel {}
