//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::WebhookEventTypeEnum;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_webhook_event_type")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub webhook_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_type: WebhookEventTypeEnum,
    #[sea_orm(
        belongs_to,
        from = "webhook_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub mega_webhook: BelongsTo<super::mega_webhook::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
