//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::ThreadStatusEnum;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_code_review_thread")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub link: String,
    pub thread_status: ThreadStatusEnum,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_one)]
    pub mega_code_review_anchor: HasOne<super::mega_code_review_anchor::Entity>,
    #[sea_orm(has_many)]
    pub mega_code_review_comments: HasMany<super::mega_code_review_comment::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
