//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_refs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique_key = "uniq_mref_path")]
    pub path: String,
    #[sea_orm(column_type = "Text", unique_key = "uniq_mref_path")]
    pub ref_name: String,
    pub ref_commit_hash: String,
    pub ref_tree_hash: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub is_cl: bool,
}

impl ActiveModelBehavior for ActiveModel {}
