//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::{DiffSideEnum, PositionStatusEnum};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_code_review_position")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub anchor_id: i64,
    pub commit_sha: String,
    pub file_path: String,
    pub diff_side: DiffSideEnum,
    pub line_number: i32,
    pub confidence: i32,
    pub position_status: PositionStatusEnum,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "anchor_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub mega_code_review_anchor: BelongsTo<super::mega_code_review_anchor::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
