//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::DiffSideEnum;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_code_review_anchor")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub thread_id: i64,
    pub file_path: String,
    pub diff_side: DiffSideEnum,
    pub anchor_commit_sha: String,
    pub original_line_number: i32,
    pub normalized_content: String,
    pub normalized_hash: String,
    pub context_before: String,
    pub context_before_hash: String,
    pub context_after: String,
    pub context_after_hash: String,
    pub created_at: DateTime,
    #[sea_orm(has_one)]
    pub mega_code_review_position: HasOne<super::mega_code_review_position::Entity>,
    #[sea_orm(
        belongs_to,
        from = "thread_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub mega_code_review_thread: BelongsTo<super::mega_code_review_thread::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
