//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::MergeStatusEnum;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_cl")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_mr_path_link")]
    pub link: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub merge_date: Option<DateTime>,
    pub status: MergeStatusEnum,
    #[sea_orm(column_type = "Text", unique_key = "idx_mr_path_link")]
    pub path: String,
    pub from_hash: String,
    pub to_hash: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub username: String,
    pub base_branch: String,
}

impl ActiveModelBehavior for ActiveModel {}
