//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_cl_commits")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub cl_link: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub commit_sha: String,
    pub author_name: String,
    pub author_email: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
}

impl ActiveModelBehavior for ActiveModel {}
