//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_webhook")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub target_url: String,
    pub secret: String,
    #[sea_orm(column_type = "Text")]
    pub event_types: String,
    pub path_filter: Option<String>,
    pub active: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub mega_webhook_deliveries: HasMany<super::mega_webhook_delivery::Entity>,
    #[sea_orm(has_many)]
    pub mega_webhook_event_types: HasMany<super::mega_webhook_event_type::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
