//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_code_review_comment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub thread_id: i64,
    pub parent_id: Option<i64>,
    pub user_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub mega_code_review_comment: BelongsTo<Option<Entity>>,
    #[sea_orm(
        belongs_to,
        from = "thread_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub mega_code_review_thread: BelongsTo<super::mega_code_review_thread::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
