//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::{PermissionEnum, ResourceTypeEnum};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_resource_permission")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_resource_permission_unique")]
    pub resource_type: ResourceTypeEnum,
    #[sea_orm(unique_key = "idx_resource_permission_unique")]
    pub resource_id: String,
    #[sea_orm(unique_key = "idx_resource_permission_unique")]
    pub group_id: i64,
    pub permission: PermissionEnum,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub mega_group: BelongsTo<super::mega_group::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
