//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_tree")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub tree_id: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub sub_trees: Vec<u8>,
    pub size: i32,
    pub created_at: DateTime,
    pub pack_id: String,
    pub pack_offset: i64,
    pub commit_id: String,
}

impl ActiveModelBehavior for ActiveModel {}
