//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "namespace_node")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub digest: String,
    pub schema_version: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::N(16384))")]
    pub canonical_bytes: Vec<u8>,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
