//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "namespace_head")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub instance_id: String,
    pub publication_seq: i64,
    pub view_id: String,
    pub writer_epoch: i64,
}

impl ActiveModelBehavior for ActiveModel {}
