//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "namespace_publication")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub instance_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub publication_seq: i64,
    pub view_id: String,
    pub parent_seq: Option<i64>,
    pub parent_view_id: Option<String>,
    pub writer_epoch: i64,
    pub actor_domain: String,
    pub operation_id: String,
    pub reason: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
