//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub public_id: String,
    pub comments_count: i32,
    pub discarded_at: Option<DateTime>,
    pub user_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub description_html: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description_state: Option<String>,
    pub description_schema_version: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub original_post_id: Option<i64>,
    pub original_digest_id: Option<i64>,
    pub visibility: i32,
    pub non_member_views_count: i32,
    pub resolved_comments_count: Option<i32>,
    pub last_activity_at: Option<DateTime>,
    pub content_updated_at: Option<DateTime>,
}

impl ActiveModelBehavior for ActiveModel {}
