//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notification_event_types")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub code: String,
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub system_required: bool,
    pub default_enabled: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub email_jobs: HasMany<super::email_jobs::Entity>,
    #[sea_orm(has_many, via = "user_notification_preferences")]
    pub user_notification_settings: HasMany<super::user_notification_settings::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
