//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "orion_tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub changes: Json,
    pub repo_name: String,
    pub cl: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub build_events: HasMany<super::build_events::Entity>,
    #[sea_orm(has_many)]
    pub build_targets: HasMany<super::build_targets::Entity>,
    #[sea_orm(has_many)]
    pub target_build_statuses: HasMany<super::target_build_status::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
