//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::CheckTypeEnum;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "path_check_configs")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "path_check_type_unique")]
    pub path: String,
    #[sea_orm(unique_key = "path_check_type_unique")]
    pub check_type_code: CheckTypeEnum,
    pub enabled: bool,
    pub required: bool,
}

impl ActiveModelBehavior for ActiveModel {}
