//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "reactions")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub public_id: String,
    pub content: Option<String>,
    pub subject_id: i64,
    pub subject_type: String,
    pub organization_membership_id: Option<i64>,
    pub username: String,
    pub discarded_at: Option<DateTime>,
}

impl ActiveModelBehavior for ActiveModel {}
