//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "snapshot_operation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub actor_domain: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub operation_id: String,
    pub instance_id: String,
    pub request_digest: String,
    pub publication_seq: Option<i64>,
    pub view_id: Option<String>,
    pub outcome: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
