//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "snapshot_instance")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub singleton: String,
    #[sea_orm(unique)]
    pub instance_id: String,
    pub created_at: DateTimeUtc,
    #[sea_orm(has_many)]
    pub snapshot_sources: HasMany<super::snapshot_source::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
