//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "snapshot_source")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_id: String,
    pub instance_id: String,
    pub kind: String,
    pub repo_id: i64,
    pub created_at: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "instance_id",
        to = "instance_id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub snapshot_instance: BelongsTo<super::snapshot_instance::Entity>,
    #[sea_orm(has_many)]
    pub source_commit_scopes: HasMany<super::source_commit_scope::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
