//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "source_commit_scope")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub scope_key: String,
    #[sea_orm(column_type = "Text")]
    pub scope_path: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub object_format: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub commit_oid: String,
    pub root_tree_oid: String,
    pub proof_kind: String,
    pub proof_oid: Option<String>,
    pub created_at: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "source_id",
        to = "source_id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub snapshot_source: BelongsTo<super::snapshot_source::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
