//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::OrionTargetStatusEnum;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "target_build_status")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_target_build_status_identity")]
    pub task_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "uq_target_build_status_identity")]
    pub target_package: String,
    #[sea_orm(column_type = "Text", unique_key = "uq_target_build_status_identity")]
    pub target_name: String,
    #[sea_orm(column_type = "Text", unique_key = "uq_target_build_status_identity")]
    pub target_configuration: String,
    #[sea_orm(column_type = "Text", unique_key = "uq_target_build_status_identity")]
    pub category: String,
    #[sea_orm(column_type = "Text", unique_key = "uq_target_build_status_identity")]
    pub identifier: String,
    #[sea_orm(column_type = "Text", unique_key = "uq_target_build_status_identity")]
    pub action: String,
    pub status: OrionTargetStatusEnum,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub orion_tasks: BelongsTo<super::orion_tasks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
