//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "target_state_histories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub build_target_id: Uuid,
    pub build_event_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub target_state: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "build_event_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub build_events: BelongsTo<super::build_events::Entity>,
    #[sea_orm(
        belongs_to,
        from = "build_target_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub build_targets: BelongsTo<super::build_targets::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
