//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_notification_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub username: String,
    pub email: String,
    pub enabled: bool,
    pub delivery_mode: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many, via = "user_notification_preferences")]
    pub notification_event_types: HasMany<super::notification_event_types::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
