//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_notification_preferences")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub username: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_type_code: String,
    pub enabled: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "event_type_code",
        to = "code",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    pub notification_event_types: BelongsTo<super::notification_event_types::Entity>,
    #[sea_orm(
        belongs_to,
        from = "username",
        to = "username",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub user_notification_settings: BelongsTo<super::user_notification_settings::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
