use std::path::PathBuf;

use anyhow::Result;
use tokio::fs;
use tracing::info;

use crate::{
    config::{TargetConfig, expand_tilde},
    handlers::ImageParams,
    keep_alive::{ImageSpec, KeepAliveMachine},
    state::{AppState, VmInfo, VmPhase},
    vm_manager,
};

type ImageSpecBuildResult = (Option<ImageSpec>, Option<u32>, Option<u32>, Option<u32>);

/// Validate inline runner environment URLs from the webhook payload.
pub fn validate_runner_env(
    server_ws: &str,
    scorpio_base_url: &str,
    scorpio_lfs_url: &str,
) -> Result<()> {
    if server_ws.trim().is_empty() {
        return Err(anyhow::anyhow!("server_ws is required"));
    }
    if scorpio_base_url.trim().is_empty() {
        return Err(anyhow::anyhow!("scorpio_base_url is required"));
    }
    if scorpio_lfs_url.trim().is_empty() {
        return Err(anyhow::anyhow!("scorpio_lfs_url is required"));
    }
    Ok(())
}

/// Handle the update request (keep_alive mode). VM stays running after this call.
///
/// `vm_name` must be pre-generated by the caller so the webhook can return it
/// immediately before this function completes.
pub async fn handle_update(
    state: &AppState,
    label: &str,
    vm_name: &str,
    target_config: TargetConfig,
    image_params: ImageParams,
) -> Result<String> {
    info!("Handling update request, label: {}, vm: {}", label, vm_name);

    let _update_guard = state.lock_update().await;
    info!("[orion-deploy] Acquired update lock for label: {}", label);

    let result = handle_update_inner(state, label, vm_name, target_config, image_params).await;
    if let Err(ref e) = result {
        tracing::error!("[orion-deploy] Update failed for {}: {:?}", vm_name, e);
        state.set_vm_failed(vm_name, e.to_string()).await;
    }
    result
}

async fn handle_update_inner(
    state: &AppState,
    label: &str,
    vm_name: &str,
    target_config: TargetConfig,
    image_params: ImageParams,
) -> Result<String> {
    let config = state.config.read().await;
    let log_dir = config.log_dir().to_string();
    let orion_source_dir = config.orion_source_dir().to_string();
    let orion_binary_path = config.orion_binary_path().to_string();
    let ssh_public_key_path = config.ssh_public_key_path().to_string();
    drop(config);

    if let Some(existing_vm) = state.get_vm().await {
        info!("Found existing VM {}, shutting down", existing_vm.id);
        if let Some(machine) = state.get_machine().await {
            machine.shutdown().await.ok();
        }
        state.clear_vm().await;
    }

    let provisioning_info = VmInfo {
        id: vm_name.to_string(),
        phase: VmPhase::Provisioning,
        ip: None,
        created_at: std::time::Instant::now(),
        log_file: None,
        error: None,
    };
    state.set_vm_provisioning(provisioning_info).await;

    info!("Creating new VM in keep_alive mode: {}", vm_name);

    let (image_config, disk_gb, cpus, memory_mb) = build_image_spec(&image_params)?;

    let machine = KeepAliveMachine::new(vm_name, image_config, disk_gb, cpus, memory_mb).await?;

    vm_manager::inject_ssh_keys(&machine, &ssh_public_key_path).await?;

    info!("[orion-deploy] Starting Orion deployment");
    vm_manager::deploy_orion_in_vm(&machine, &orion_source_dir, &orion_binary_path).await?;

    vm_manager::replace_env_vars_in_vm(&machine, &target_config, label).await?;

    let logs = vm_manager::start_orion_in_vm(&machine).await?;

    let log_file = save_orion_logs(&log_dir, vm_name, &logs).await?;

    let vm_ip = machine.get_ip().await.ok().flatten();
    info!("[orion-deploy] VM IP: {:?}", vm_ip);

    let vm_info = VmInfo {
        id: vm_name.to_string(),
        phase: VmPhase::Running,
        ip: vm_ip,
        created_at: std::time::Instant::now(),
        log_file: Some(log_file.clone()),
        error: None,
    };
    state.set_vm(vm_info, machine).await;

    info!("Update completed successfully for label: {}", label);
    Ok(vm_name.to_string())
}

fn build_image_spec(params: &ImageParams) -> Result<ImageSpecBuildResult> {
    let path = params.path.as_ref();
    let url = params.url.as_ref();
    let digest = params.digest.as_ref();

    if path.is_some() && url.is_some() {
        return Err(anyhow::anyhow!(
            "image_path and image_url cannot both be set"
        ));
    }

    if (path.is_some() || url.is_some()) && digest.is_none() {
        return Err(anyhow::anyhow!(
            "image_digest is required when image_path or image_url is provided"
        ));
    }

    let img_spec = match (url, path, digest) {
        (Some(url), None, Some(digest)) => {
            info!("[orion-deploy] Using image from URL: {}", url);
            Some(ImageSpec {
                source: Some(url.clone()),
                digest: Some(digest.clone()),
            })
        }
        (None, Some(path), Some(digest)) => {
            let expanded = expand_tilde(path);
            let path_str = expanded.to_string_lossy().into_owned();
            if path != &path_str {
                info!(
                    "[orion-deploy] Using image from path: {} (expanded from {})",
                    path_str, path
                );
            } else {
                info!("[orion-deploy] Using image from path: {}", path_str);
            }
            if !expanded.is_file() {
                return Err(anyhow::anyhow!(
                    "image file does not exist: {} (from image_path: {})",
                    path_str,
                    path
                ));
            }
            Some(ImageSpec {
                source: Some(path_str),
                digest: Some(digest.clone()),
            })
        }
        (None, None, _) => {
            info!("[orion-deploy] No image source in params, using default Debian image");
            None
        }
        _ => unreachable!(),
    };

    Ok((img_spec, params.disk_gb, params.cpus, params.memory_mb))
}

const ORION_LOG_PATH: &str = "/home/orion/orion-runner/log/orion.log";
const ORION_LOG_BOOTSTRAP_BYTES: u64 = 65536;

pub struct LiveLogSnapshot {
    pub journal_window: String,
    pub orion_log_delta: String,
    pub orion_log_offset: u64,
}

pub async fn get_live_logs_since(
    state: &AppState,
    orion_log_offset: u64,
) -> Result<LiveLogSnapshot> {
    let machine = state
        .get_machine()
        .await
        .ok_or_else(|| anyhow::anyhow!("No VM is currently running"))?;

    let output = machine
        .exec("journalctl -u orion-runner --no-pager -n 200 2>&1")
        .await?;

    let size_output = machine
        .exec(&format!("stat -c%s {ORION_LOG_PATH} 2>/dev/null || echo 0"))
        .await?;
    let file_size: u64 = String::from_utf8_lossy(&size_output.stdout)
        .trim()
        .parse()
        .unwrap_or(0);

    let (orion_log_delta, new_offset) = if file_size < orion_log_offset {
        let out = machine
            .exec(&format!("cat {ORION_LOG_PATH} 2>/dev/null"))
            .await?;
        (String::from_utf8_lossy(&out.stdout).into_owned(), file_size)
    } else if file_size > orion_log_offset {
        let read_from = if orion_log_offset == 0 {
            file_size.saturating_sub(ORION_LOG_BOOTSTRAP_BYTES)
        } else {
            orion_log_offset
        };
        let cmd = if read_from == 0 {
            format!("cat {ORION_LOG_PATH} 2>/dev/null")
        } else {
            format!("tail -c +{} {ORION_LOG_PATH} 2>/dev/null", read_from + 1)
        };
        let out = machine.exec(&cmd).await?;
        (String::from_utf8_lossy(&out.stdout).into_owned(), file_size)
    } else {
        (String::new(), orion_log_offset)
    };

    Ok(LiveLogSnapshot {
        journal_window: String::from_utf8_lossy(&output.stdout).into_owned(),
        orion_log_delta,
        orion_log_offset: new_offset,
    })
}

pub async fn get_status(state: &AppState) -> Option<VmInfo> {
    state.get_vm().await
}

pub async fn get_scorpio_status(state: &AppState) -> Result<serde_json::Value> {
    let machine = state
        .get_machine()
        .await
        .ok_or_else(|| anyhow::anyhow!("No VM is currently running"))?;

    info!("[scorpio] Checking mount status and directories");

    let paths = vec![
        ("workspace", "/workspace/mount"),
        ("store_path", "/data/scorpio/store"),
        ("antares_upper", "/data/scorpio/antares/upper"),
        ("antares_cl", "/data/scorpio/antares/cl"),
        ("antares_mount", "/data/scorpio/antares/mnt"),
    ];

    let mut results = serde_json::Map::new();

    for (name, path) in paths {
        let exists_output = machine
            .exec(&format!(
                "test -e {} && echo 'exists' || echo 'not_found'",
                path
            ))
            .await?;
        let exists = String::from_utf8_lossy(&exists_output.stdout).contains("exists");

        let mount_output = machine
            .exec(&format!(
                "mountpoint -q {} && echo 'mounted' || echo 'not_mounted'",
                path
            ))
            .await?;
        let is_mounted = String::from_utf8_lossy(&mount_output.stdout).contains("mounted");

        let file_count = if exists {
            let count_output = machine
                .exec(&format!(
                    "find {} -maxdepth 1 -type f 2>/dev/null | wc -l",
                    path
                ))
                .await?;
            String::from_utf8_lossy(&count_output.stdout)
                .trim()
                .to_string()
        } else {
            "N/A".to_string()
        };

        let dir_count = if exists {
            let count_output = machine
                .exec(&format!(
                    "find {} -maxdepth 1 -type d 2>/dev/null | wc -l",
                    path
                ))
                .await?;
            String::from_utf8_lossy(&count_output.stdout)
                .trim()
                .to_string()
        } else {
            "N/A".to_string()
        };

        let contents: String = if exists {
            let ls_output = machine
                .exec(&format!("ls -la {} 2>/dev/null | head -20", path))
                .await?;
            String::from_utf8_lossy(&ls_output.stdout).into_owned()
        } else {
            "N/A".to_string()
        };

        results.insert(
            name.to_string(),
            serde_json::json!({
                "path": path,
                "exists": exists,
                "is_mounted": is_mounted,
                "file_count": file_count,
                "dir_count": dir_count,
                "contents": contents
            }),
        );
    }

    let mount_output = machine.exec("mount | grep -E '(workspace|megadir|scorpio|antares)' || echo 'No relevant mounts found'").await?;
    let mount_info = String::from_utf8_lossy(&mount_output.stdout);

    let orion_output = machine
        .exec("pgrep -a orion || echo 'Orion not running'")
        .await?;
    let orion_info = String::from_utf8_lossy(&orion_output.stdout);

    let scorpio_output = machine
        .exec("pgrep -a scorpio || echo 'Scorpio not running'")
        .await?;
    let scorpio_info = String::from_utf8_lossy(&scorpio_output.stdout);

    let network_test = machine.exec("curl -sI --connect-timeout 5 https://git.gitmega.com 2>&1 | head -5 || echo 'Connection failed'").await?;
    let network_info = String::from_utf8_lossy(&network_test.stdout);

    let status = serde_json::json!({
        "status": "ok",
        "directories": results,
        "mounts": mount_info,
        "orion_process": orion_info,
        "scorpio_process": scorpio_info,
        "network_test": {
            "git.gitmega.com": network_info.trim()
        }
    });

    Ok(status)
}

async fn save_orion_logs(log_dir: &str, vm_name: &str, logs: &str) -> Result<String> {
    fs::create_dir_all(log_dir).await?;

    let log_file_name = format!("{}-{}.log", vm_name, chrono_lite_timestamp());
    let log_file_path = PathBuf::from(log_dir).join(&log_file_name);

    fs::write(&log_file_path, logs).await?;

    info!("[orion-logs] Saved logs to: {}", log_file_path.display());
    Ok(log_file_path.to_string_lossy().into_owned())
}

pub fn chrono_lite_timestamp() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let duration = SystemTime::now().duration_since(UNIX_EPOCH).unwrap();
    format!("{}", duration.as_secs())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::handlers::ImageParams;

    #[test]
    fn build_image_spec_from_url_params() {
        let params = ImageParams {
            path: None,
            url: Some("https://example.com/image.qcow2".into()),
            digest: Some("sha256:abc".into()),
            disk_gb: Some(30),
            cpus: Some(8),
            memory_mb: Some(16000),
        };
        let (spec, disk, cpus, mem) = build_image_spec(&params).unwrap();
        assert!(spec.is_some());
        assert_eq!(disk, Some(30));
        assert_eq!(cpus, Some(8));
        assert_eq!(mem, Some(16000));
    }
}
